[build]
  command = "bun run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/api"
  status = 200
  force = true
